FlightManager/FlightManager/ViewModels/Shared/PagingViewModel.cs
namespace FlightManager.ViewModels.Shared
{
    using System;
    public class PagingViewModel
    {
        public PagingViewModel(int itemsPerPage = 5, string action = "Index")
        {
            this.ItemsPerPage = itemsPerPage;
            this.Action = action;
            this.PageNumber = 1;
        }
        public int PageNumber { get; set; }
        public bool HasPreviousPage => this.PageNumber > 1;
        public int PreviousPageNumber => this.PageNumber - 1;
        public bool HasNextPage => this.PageNumber < this.PagesCount;
        public int NextPageNumber => this.PageNumber + 1;
        public int PagesCount => (int)Math.Ceiling((double)this.ElementsCount / this.ItemsPerPage);
        public int ElementsCount { get; set; }
        public int ItemsPerPage { get; set; }
        public string Action { get; set; }
    }
}

FlightManager/FlightManager/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlightManager.Data;
using FlightManager.Data.Models;
using Microsoft.AspNetCore.Authorization;
using FlightManager.Services;

namespace FlightManager.Controllers
{
    [Authorize]
    public class FlightsController : Controller
    {
        private readonly IFlightsService flightsService;

        public FlightsController(IFlightsService flightsService)
        {
            this.flightsService = flightsService;
        }

        // GET: Flights
        public async Task<IActionResult> Index()
        {
            return View(await flightsService.GetFlightsAsync());
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await flightsService.GetFlightByIdAsync((int)id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: Flights/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PilotName,FlightFrom,FlightTo,LiftOff,LandOn,TypeOfPlane,UniqueNumber,CapacityPassengers,CapacityBusinessClass")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                await flightsService.CreateFlightASync(flight);
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await flightsService.FindFlightAsync((int)id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PilotName,FlightFrom,FlightTo,LiftOff,LandOn,TypeOfPlane,UniqueNumber,CapacityPassengers,CapacityBusinessClass")] Flight flight)
        {
            if (id != flight.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await flightsService.UpdateFlightAsync(flight);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await flightsService.GetIdToDelete((int)id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flight = await flightsService.FindFlightAsync(id);
            await flightsService.DeleteFlightConfirmedAsync(flight);
            return RedirectToAction(nameof(Index));
        }

        private bool FlightExists(int id)
        {
            return flightsService.CheckFlightExist(id);
        }
    }
}

FlightManager/FlightManager/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlightManager.Data;
using FlightManager.Data.Models;
using Microsoft.AspNetCore.Authorization;
using FlightManager.ViewModels.Reservations;
using Microsoft.AspNetCore.Identity;

namespace FlightManager.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<User> userManager;

        public ReservationsController(AppDbContext context, UserManager<User> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        // GET: Reservations
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Reservations.Include(r => r.Flight);
            return View(await appDbContext.ToListAsync());
        }

        public IActionResult NotAvailableFlights()
        {
            return this.View();
        }
        [Authorize]
        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Flight)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create
        public IActionResult Create()
        {
            if (!_context.Flights.Any(x => x.LiftOff > DateTime.UtcNow))
            {
                return RedirectToAction(nameof(NotAvailableFlights));
            }
            ViewData["FlightId"] = new SelectList(_context.Flights.Where(x => x.LiftOff > DateTime.Now), "Id", "UniqueNumber");
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FlightId,Email,PassangersCount")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                var reservationId = _context.Reservations.OrderByDescending(x => x.Id).FirstOrDefault().Id;

                return RedirectToAction(nameof(Create), "Passangers", new { reservationId });

            }
            ViewData["FlightId"] = new SelectList(_context.Flights, "Id", "UniqueNumber", reservation.FlightId);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            EditReservationViewModel model = new EditReservationViewModel()
            {
                Id = reservation.Id,
                PassangersCount = reservation.PassangersCount,
                IsConfirmed = reservation.IsConfirmed,
                Email = reservation.Email,
                UserConfirmedAccount=reservation.User!=null?$"{reservation.User.FirstName} {reservation.User.LastName}":"n/a"
            };

            Flight flight = await _context.Flights.FindAsync(reservation.FlightId);

            model.Flight = new FlightReservationViewModel()
            {
                Id = flight.Id,
                FlightFrom = flight.FlightFrom,
                FlightTo = flight.FlightTo,
                LiftOff = flight.LiftOff,
                LandOn = flight.LandOn,
                PilotName = flight.PilotName,
                TypeOfPlane = flight.TypeOfPlane,
                UniqueNumber = flight.UniqueNumber
            };

            model.Passangers = reservation
                .Passangers
                .Select(x => new PassangerReservationViewModel()
                {
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    PhoneNumber = string.IsNullOrWhiteSpace(x.PhoneNumber)? "n/a" : x.PhoneNumber,
                    TypeOfTicket = x.TypeOfTicket
                })
                .ToList();
            return View(model);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IsConfirmed,Email")] Reservation reservation)
        {
            if (id != reservation.Id)
            {
                return NotFound();
            }
            Reservation editReservation = await _context.Reservations.FindAsync(id);
            editReservation.IsConfirmed = reservation.IsConfirmed;
            editReservation.User = await userManager.GetUserAsync(this.User);
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(editReservation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(editReservation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FlightId"] = new SelectList(_context.Flights, "Id", "Id", reservation.FlightId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .Include(r => r.Flight)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservations.FindAsync(id);
            _context.Reservations.Remove(reservation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservations.Any(e => e.Id == id);
        }
    }
}

FlightManager/FlightManager/Controllers/UsersController.cs
using FlightManager.Services;
using FlightManager.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace FlightManager.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService usersService)
        {
            this.usersService = usersService;
        }
        public async Task<IActionResult> Index(int page = 1, int itemsPerPage = 10)
        {
            var model = new IndexUsersViewModel() { PageNumber = page, ItemsPerPage = itemsPerPage };
            IndexUsersViewModel newModel = await usersService.GetUsersAsync(model);
            return View(newModel);
        }
        [HttpPost]
        public async Task<IActionResult> Index(IndexUsersViewModel model)
        {
            IndexUsersViewModel newModel = await usersService.GetUsersAsync(model);
            return View(newModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await usersService.CreateUserAsync(model);
            return RedirectToAction(nameof(this.Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            EditUserViewModel model = await usersService.GetUserToEdit(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await usersService.EditUserAsync(model);
            return RedirectToAction(nameof(this.Index));
        }
        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            DetailsUserViewModel model = await usersService.GetUserDetailsAsync(id);
            return View(model);
        }
    }
}

FlightManager/FlightManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlightManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/345b56ec9d.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FlightManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Index">Flights</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservation</a>
                            </li>
                        }
                        else if (this.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Index">Flights</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservation</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Create">Book flight</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FlightManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FlightManager/FlightManager/Views/Shared/_PagingPartial.cshtml
@using FlightManager.ViewModels.Shared
@model PagingViewModel
<nav aria-label="..." class="">

    <ul class="pagination  justify-content-center ">
        <li>
            <div class="btn-group">
                <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @Model.ItemsPerPage
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-route-page="@Model.PageNumber" asp-route-itemsperpage="5">5</a>
                    <a class="dropdown-item" asp-route-page="@Model.PageNumber" asp-route-itemsperpage="10">10</a>
                    <a class="dropdown-item" asp-route-page="@Model.PageNumber" asp-route-itemsperpage="25">25</a>
                    <a class="dropdown-item" asp-route-page="@Model.PageNumber" asp-route-itemsperpage="50">50</a>
                </div>
            </div>
        </li>
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.PreviousPageNumber" asp-route-itemsperpage="@Model.ItemsPerPage">
                <i class="fas fa-step-backward"></i>

            </a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i" asp-route-itemsperpage="@Model.ItemsPerPage">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i" asp-route-itemsperpage="@Model.ItemsPerPage">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.NextPageNumber" asp-route-itemsperpage="@Model.ItemsPerPage"><i class="fas fa-step-forward"></i></a>
        </li>
    </ul>
</nav>